### ISSUE TITLE
[!!] Data conversion

### ISSUE THREAD

**Issue by Acumane** [Vacansee/data#1]
```json
{
	"crse": 2500,
	"id": "CSCI-2500",
	"sections": [
	  {
		"act": 34,
		"attribute": "",
		"cap": 38,
		"credMax": 4.0,
		"credMin": 4.0,
		"crn": 77275,
		"crse": 2500,
		"rem": 4,
		"sec": "01",
		"subj": "CSCI",
		"timeslots": [
		  {
			"dateEnd": "05/05",
			"dateStart": "01/09",
			"days": [
			  "M",
			  "R"
			],
			"instructor": "George M. Slota",
			"location": "Darrin Communications Center 318",
			"timeEnd": 1550,
			"timeStart": 1400
			...
```
^^ snippet of `courses.json` from SIS that's 253 lines long

Prune and convert this into a representation much more befitting of our use case. A few ideas (in TOML, but might stick w/ JSON):
```toml
[DCC.3.18]       # sort by building & floor #
    mon = [ [1400, 1550], [1800, 1950, "T"] ]   # tag likely test blocks (T)
    fri = [ [1400, 1550] ]
    fits = 153  # approx room size, sum of all *concurrent* sections

[Sage.5.101]
    wed = [ [800, 950], [1000, 1150], [1200, 1350], [1600, 1750] ]
    fits = 40   # approx room size, largest single session
```

```toml
mon = [         # ordered array; binary search over day[][0]
    # time
    [ 1400, ["DCC.3.18"],   # begin[]
            []              # end[]
    ],
    [ 1550, [], 
            ["DCC.3.18"]
    ],
    [ 1800, ["DCC.3.18"],
            []
    ],
    [ 1950, [],
            ["DCC.3.18"]
    ],
]

wed = [
    [ 800, ["Sage.5.101"], [] ],
    [ 950, [], ["Sage.5.101"] ],
    [ 1000, ["Sage.5.101"], [] ],
    [ 1150, [], ["Sage.5.101"] ],
    [ 1200, ["Sage.5.101"], [] ],
    [ 1350, [], ["Sage.5.101"] ],
    [ 1600, ["Sage.5.101"], [] ],
    [ 1750, [], ["Sage.5.101"] ],
]

fri = [
    [ 1400, ["DCC.3.18"], [] ],
    [ 1550, [], ["DCC.3.18"] ],
]
```

```toml
# abbreviate building names:
DCC = "Darrin Communications Center"
Sage = "Russell Sage Laboratory" 
```
